Repository Groom-Team11/Back, pull requests merged in 2024-09, with the labels that each got.

#3 [CHORE] 초기 프로젝트 세팅
  build.gradle
  src/main/java/com/bloomgroom/BloomGroomApplication.java
  src/main/java/com/bloomgroom/global/config/YamlPropertySourceFactory.java
  src/main/java/com/bloomgroom/global/payload/ApiResponse.java
  src/main/java/com/bloomgroom/global/payload/ErrorCode.java
  src/main/java/com/bloomgroom/global/payload/ErrorResponse.java
  src/main/java/com/bloomgroom/global/payload/Message.java
  src/main/java/com/bloomgroom/global/payload/exception/BusinessBaseException.java
  src/main/java/com/bloomgroom/global/payload/exception/GlobalExceptionHandler.java
  src/main/java/com/bloomgroom/global/payload/exception/NotFoundException.java
  src/main/resources/application.yml
Labels: 🍀chore

#8 [Feat] 세부목표 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/bloomgroom/BloomGroomApplication.java
  src/main/java/com/bloomgroom/domain/smallgoal/application/SmallGoalService.java
  src/main/java/com/bloomgroom/domain/smallgoal/domain/SmallGoal.java
  src/main/java/com/bloomgroom/domain/smallgoal/domain/repository/SmallGoalRepository.java
  src/main/java/com/bloomgroom/domain/smallgoal/dto/request/CreateSmallGoalReq.java
  src/main/java/com/bloomgroom/domain/smallgoal/dto/request/SmallGoalDateReq.java
  src/main/java/com/bloomgroom/domain/smallgoal/dto/request/UpdateSmallGoalReq.java
  src/main/java/com/bloomgroom/domain/smallgoal/dto/response/SmallGoalRes.java
  src/main/java/com/bloomgroom/domain/smallgoal/presentation/SmallGoalController.java
  src/main/java/com/bloomgroom/domain/user/application/TokenService.java
  src/main/java/com/bloomgroom/domain/user/application/UserService.java
  src/main/java/com/bloomgroom/domain/user/domain/RefreshToken.java
  src/main/java/com/bloomgroom/domain/user/domain/User.java
  src/main/java/com/bloomgroom/domain/user/domain/repository/RefreshTokenRepository.java
  src/main/java/com/bloomgroom/domain/user/domain/repository/UserRepository.java
  src/main/java/com/bloomgroom/domain/user/dto/request/KakaoTokenReq.java
  src/main/java/com/bloomgroom/domain/user/dto/request/TokenReq.java
  src/main/java/com/bloomgroom/domain/user/dto/response/BasicResponse.java
  src/main/java/com/bloomgroom/domain/user/dto/response/KakaoLoginRes.java
  src/main/java/com/bloomgroom/domain/user/dto/response/KakaoTokenRes.java
  src/main/java/com/bloomgroom/domain/user/presentation/UserController.java
  src/main/java/com/bloomgroom/domain/user/security/CustomUserDetails.java
  src/main/java/com/bloomgroom/domain/user/security/CustomUserDetailsService.java
  src/main/java/com/bloomgroom/domain/user/security/JwtAuthenticationFilter.java
  src/main/java/com/bloomgroom/global/config/SecurityConfig.java
  src/main/java/com/bloomgroom/global/config/YamlPropertySourceFactory.java
  src/main/java/com/bloomgroom/global/payload/ApiResponse.java
  src/main/java/com/bloomgroom/global/payload/ErrorCode.java
  src/main/java/com/bloomgroom/global/payload/ErrorResponse.java
  src/main/java/com/bloomgroom/global/payload/Message.java
  src/main/java/com/bloomgroom/global/payload/exception/BusinessBaseException.java
  src/main/java/com/bloomgroom/global/payload/exception/GlobalExceptionHandler.java
  src/main/java/com/bloomgroom/global/payload/exception/NotFoundException.java
  src/main/resources/application.yml
  src/main/resources/database/application-database.yml
  src/main/resources/oauth2/application-oauth2.yml
Labels: enhancement

#12 [Fix] 날짜별 세부기능 조회 url 수정
  src/main/java/com/bloomgroom/domain/smallgoal/presentation/SmallGoalController.java
Labels: 🔧fix

#13 [CHORE] CICD 및 인프라 구축
  .github/workflows/aws.yml
  src/main/java/com/bloomgroom/BloomGroomApplication.java
  src/main/java/com/bloomgroom/global/config/AppConfig.java
  src/main/java/com/bloomgroom/global/config/S3Config.java
  src/main/java/com/bloomgroom/global/config/SwaggerConfig.java
  src/main/java/com/bloomgroom/global/config/WebMvcConfig.java
Labels: 🍀chore

#16 [CHORE] appspec.yml 추가
  appspec.yml
Labels: 🍀chore

#17 [CHORE] appspec.yml 파일 추가
  appspec.yml
Labels: 🍀chore

#19 [CHORE] SecurityConfig swagger 추가 및 application.yml 추가
  src/main/java/com/bloomgroom/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🍀chore

#20 Merge develop to main
  src/main/java/com/bloomgroom/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🍀chore

#21 [CHORE] SecurityConfig 수정
  src/main/java/com/bloomgroom/global/config/SecurityConfig.java
Labels: 🍀chore

#22 [CHORE] SecurityConfig 수정
  src/main/java/com/bloomgroom/global/config/SecurityConfig.java
Labels: 🍀chore

#25 [HOTFIX] appspec 수정
  appspec.yml
Labels: 🍀chore, 🔥hotfix

#30 [Feat] 스웨거 태그 추가
  src/main/java/com/bloomgroom/domain/biggoal/presentation/BigGoalController.java
  src/main/java/com/bloomgroom/domain/smallgoal/presentation/SmallGoalController.java
Labels: enhancement

#32 [Feat] 꽃 기능 구현
  src/main/java/com/bloomgroom/domain/flower/application/FlowerDictionaryService.java
  src/main/java/com/bloomgroom/domain/flower/domain/Flower.java
  src/main/java/com/bloomgroom/domain/flower/domain/FlowerDictionary.java
  src/main/java/com/bloomgroom/domain/flower/domain/repository/FlowerDictionaryRepository.java
  src/main/java/com/bloomgroom/domain/flower/domain/repository/FlowerRepository.java
  src/main/java/com/bloomgroom/domain/flower/dto/response/FlowerDetailRes.java
  src/main/java/com/bloomgroom/domain/flower/dto/response/FlowerListRes.java
  src/main/java/com/bloomgroom/domain/flower/dto/response/NewFlowerRes.java
  src/main/java/com/bloomgroom/domain/flower/presentation/FlowerController.java
  src/main/java/com/bloomgroom/domain/user/presentation/UserController.java
Labels: ✨feature

#35 [Fix] 날짜별 상세목표 조회 API Response값 수정
  src/main/java/com/bloomgroom/domain/smallgoal/application/SmallGoalService.java
  src/main/java/com/bloomgroom/global/payload/ApiResponse.java
Labels: 🔧fix

#36 [Fix] Transactional 누락 수정
  src/main/java/com/bloomgroom/domain/flower/application/FlowerDictionaryService.java
Labels: 🔧fix

#38 [Fix] 사용자 도감 생성 로직 수정
  src/main/java/com/bloomgroom/domain/flower/application/FlowerDictionaryService.java
Labels: 🔧fix

#44 [Feat] 수증기 API 구현
  src/main/java/com/bloomgroom/domain/steam/application/SteamService.java
  src/main/java/com/bloomgroom/domain/steam/domain/Steam.java
  src/main/java/com/bloomgroom/domain/steam/domain/repository/SteamRepository.java
  src/main/java/com/bloomgroom/domain/steam/dto/response/SteamRes.java
  src/main/java/com/bloomgroom/domain/steam/presentation/SteamController.java
Labels: enhancement

#46 [Fix] 수증기 APIResponse
  src/main/java/com/bloomgroom/domain/steam/application/SteamService.java
  src/main/java/com/bloomgroom/domain/steam/dto/response/SteamRes.java
  src/main/java/com/bloomgroom/domain/steam/presentation/SteamController.java
Labels: 🔧fix

#58 [Fix] SmallGoal 클래스에서 BigGoalId JsonIgnore 추가
  gradlew
  src/main/java/com/bloomgroom/domain/smallgoal/domain/SmallGoal.java
Labels: 🔧fix

#59 [Fix] fix calculating achievement method
  src/main/java/com/bloomgroom/domain/biggoal/application/BigGoalService.java
Labels: 🔧fix

#62 Merge develop to main
  src/main/java/com/bloomgroom/domain/user/presentation/UserController.java
  src/main/java/com/bloomgroom/global/payload/ApiResponse.java
Labels: ✨feature, 🔧fix
